version: '3.8'

services:
  data:
    build:
      context: ./src/data
      dockerfile: Dockerfile
    volumes:
      - ./src/data/processed_data:/app/processed_data

  models:
    build:
      context: ./src/models
      dockerfile: Dockerfile
    depends_on:
      - data
    volumes:
      - ./src/data/processed_data:/app/processed_data  
      - ./src/models/results:/app/results 
