version: '3.8'

services:
  data:
    build:
      context: ./src/data
      dockerfile: Dockerfile
    volumes:
      - ./src/data/processed_data:/app/processed_data
    command: python scripts/process_data.py

  models:
    build:
      context: ./src/models
      dockerfile: Dockerfile
    depends_on:
      - data
    volumes:
      - ./src/data/processed_data:/app/processed_data
      - ./src/models/results:/app/results
    command: python scripts/correlation_analysis.py /app/processed_data/processed_data.csv
